#!/usr/bin/env bash
# Generate .env.worktree with isolated DB name + unique ports when running
# from a git worktree (or on explicit opt-in).
#
# Borrowed from multica's pattern — each worktree/branch gets its own
# PostgreSQL database and port offset so migrations never fight.
#
# Usage:
#   scripts/worktree-env.sh          # auto: writes .env.worktree iff in a worktree
#   scripts/worktree-env.sh --force  # force-write regardless of worktree status
#
# The generated file only overrides *ports* and *database names*. It is
# intended to be sourced/loaded alongside .env (not as a replacement).
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT_DIR"

FORCE=0
if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
fi

GIT_DIR=$(git rev-parse --git-dir)
COMMON_DIR=$(git rev-parse --git-common-dir)
IS_WORKTREE=0
if [[ "$GIT_DIR" != "$COMMON_DIR" && "$GIT_DIR" != ".git" ]]; then
  IS_WORKTREE=1
fi

if [[ $IS_WORKTREE -eq 0 && $FORCE -eq 0 ]]; then
  echo "Not a git worktree (and --force not set). Use .env as-is."
  exit 0
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD | tr -c 'a-zA-Z0-9' '_' | tr -s '_' | sed 's/_$//' | tr '[:upper:]' '[:lower:]')
if [[ -z "$BRANCH" || "$BRANCH" == "HEAD" ]]; then
  BRANCH="detached"
fi

# Compute a stable offset in [1..40] in Python to avoid bash int overflow.
OFFSET=$(python3 -c "import hashlib,sys; h=int(hashlib.sha1(sys.argv[1].encode()).hexdigest(),16); print((h % 40) + 1)" "$ROOT_DIR")

API_PORT=$((8000 + OFFSET))
WEB_PORT=$((3000 + OFFSET))
PG_PORT=$((5432 + OFFSET))
REDIS_PORT=$((6379 + OFFSET))
NEO4J_BOLT_PORT=$((7687 + OFFSET))
NEO4J_HTTP_PORT=$((7474 + OFFSET))

DB_NAME="memstack_${BRANCH}"

OUT=.env.worktree
cat > "$OUT" <<EOF
# Auto-generated by scripts/worktree-env.sh — do not edit manually.
# Branch: $BRANCH
# Worktree: $ROOT_DIR
# Port offset: +$OFFSET
API_PORT=$API_PORT
WEB_PORT=$WEB_PORT
POSTGRES_PORT=$PG_PORT
POSTGRES_DB=$DB_NAME
REDIS_PORT=$REDIS_PORT
NEO4J_BOLT_PORT=$NEO4J_BOLT_PORT
NEO4J_HTTP_PORT=$NEO4J_HTTP_PORT
NEO4J_URI=bolt://localhost:$NEO4J_BOLT_PORT
EOF

echo "Wrote $OUT:"
cat "$OUT" | sed 's/^/  /'
